//ALL ITEMS LIST
export const ITEM_LIST_LOADING = "ITEM_LIST_LOADING";
export const ITEM_LIST_SUCCESS = "ITEM_LIST_SUCCESS";
export const ITEM_LIST_FAILED = "ITEM_LIST_FAILED";
export const ITEM_DELETE = "ITEM_DELETE";

//EACH ITEM
export const ITEM_LOADING = "ITEM_LOADING";
export const ITEM_SUCCESS = "ITEM_SUCCESS";
export const ITEM_FAILED = "ITEM_FAILED";

//PAGE
export const CURRENT_PAGE = "CURRENT_PAGE";

